import type { BootstrapResult } from "./types";

export const demoBootstrap: BootstrapResult = {
  demoMode: true,
  developmentData: false,
  storagePath: "Browser preview — no settings are written",
  environment: {
    git: { available: true, version: "git version 2.53.0.windows.2" },
    gh: { available: true, version: "gh version 2.0.0" },
    ssh: { available: true, version: "OpenSSH for Windows" },
    sshDirectory: "C:\\Users\\you\\.ssh",
  },
  data: {
    version: 1,
    profiles: [
      {
        id: "open-source",
        label: "Open Source",
        accent: "#d8a33f",
        gitName: "Your Name",
        gitEmail: "personal@example.com",
        githubUsername: "your-personal",
        sshKeyPath: "C:\\Users\\you\\.ssh\\id_ed25519_oss",
        ghConfigDir: "C:\\Users\\you\\.config\\gh-open-source",
        autoApprove: { cloneRepository: false },
      },
      {
        id: "university-lab",
        label: "University Lab",
        accent: "#56a7d9",
        gitName: "Your Name",
        gitEmail: "student@example.com",
        githubUsername: "your-school",
        sshKeyPath: "C:\\Users\\you\\.ssh\\id_ed25519_lab",
        ghConfigDir: "C:\\Users\\you\\.config\\gh-university-lab",
        autoApprove: { cloneRepository: false },
      },
      {
        id: "client-work",
        label: "Client Work",
        accent: "#D97866",
        gitName: "Example Contributor",
        gitEmail: "client@example.com",
        githubUsername: "example-client",
        sshKeyPath: "C:\\Users\\you\\.ssh\\id_ed25519_client",
        ghConfigDir: "C:\\Users\\you\\.config\\gh-client-work",
        autoApprove: { cloneRepository: false },
      },
    ],
    repositories: [
      {
        id: "repo-personal",
        name: "weekend-game",
        path: "C:\\Users\\you\\Projects\\personal\\weekend-game",
        remoteUrl: "git@github.com:your-personal/weekend-game.git",
        branch: "main",
        profileId: "open-source",
        lastAppliedAt: "2026-08-26T00:20:00Z",
        autoApprove: { pushWorkBranch: false, pushDefaultBranch: false, createPullRequest: false, mergePullRequest: false, publishRepository: false },
      },
      {
        id: "repo-school",
        name: "compiler-class",
        path: "C:\\Users\\you\\Projects\\school\\compiler-class",
        remoteUrl: "git@github.com:your-school/compiler-class.git",
        branch: "main",
        profileId: "university-lab",
        lastAppliedAt: "2026-08-25T11:05:00Z",
        autoApprove: { pushWorkBranch: false, pushDefaultBranch: false, createPullRequest: false, mergePullRequest: false, publishRepository: false },
      },
      {
        id: "repo-reapply",
        name: "design-notes",
        path: "C:\\Users\\you\\Projects\\personal\\design-notes",
        remoteUrl: "git@github.com:your-personal/design-notes.git",
        branch: "feature/layout",
        profileId: "open-source",
        lastAppliedAt: "2026-08-20T00:20:00Z",
        autoApprove: { pushWorkBranch: false, pushDefaultBranch: false, createPullRequest: false, mergePullRequest: false, publishRepository: false },
      },
      {
        id: "repo-attention",
        name: "archive-tools",
        path: "C:\\Users\\you\\Projects\\school\\archive-tools",
        remoteUrl: "git@github.com:example-client/archive-tools.git",
        branch: "main",
        profileId: "client-work",
        lastAppliedAt: "2026-08-22T00:20:00Z",
        autoApprove: { pushWorkBranch: false, pushDefaultBranch: false, createPullRequest: false, mergePullRequest: false, publishRepository: false },
      },
      {
        id: "repo-unassigned",
        name: "new-research",
        path: "C:\\Users\\you\\Projects\\new-research",
        remoteUrl: "git@github.com:example/new-research.git",
        branch: "develop",
        profileId: null,
        lastAppliedAt: null,
        autoApprove: { pushWorkBranch: false, pushDefaultBranch: false, createPullRequest: false, mergePullRequest: false, publishRepository: false },
      },
    ],
  },
};
